### ISSUE TITLE
[Member] 회원가입 페이지 구현

### ISSUE THREAD

**Issue by juneheel** [Team-SE-MO/semo-react-server#10]
## 📄 설명
- 서비스 등록, 회사등록 팝업 페이지 구현, 로고와 푸터 구현 진행

## 🗓️ TO-DO
- [x] 서비스 등록 페이지
- [x] 회사 등록 모달
- [x] 로고 atom 구현
- [x] 헤더,푸터 구현 -> 공통 메인 레이아웃 구현
