### ISSUE TITLE
[Member, Company] 회원가입, 회사등록 API 연결

### ISSUE THREAD

**Issue by taeyeon721** [Team-SE-MO/semo-react-server#32]
## 📄 설명
- 회원가입 및 회사등록 기능에 대한 API 연결 작업을 진행합니다. 사용자 계정 등록 폼 제출과 회사 등록 폼 제출 기능이 백엔드와 연동되어 원활하게 작동할 수 있도록 합니다.

## 🗓️ TO-DO
- [x] 이메일 중복 확인 API 연결
- [x] 회사 목록 조회 API 연결
- [x] 회원가입 API 연결
- [x] 회사등록 API 연결
