### ISSUE TITLE
[Global] sweetAlert 적용

### ISSUE THREAD

**Issue by dabeen-jung** [Team-SE-MO/semo-react-server#41]
## 📄 설명
- 기존 코드 sweetAlert 교체 적용
- alert 필요한 부분 적용

## 🗓️ TO-DO
- [ ] Alert -> SweetAlert으로 교체
- [x] form 기반 alert 교체
- [ ] error기반 alert 교체

### ➕ ETC
- 장비 부분의 경우api 생성 및 연결 후 sweetAlert의 필요여부에 따라 추가가 될 수 있습니다
