### ISSUE TITLE
[Global] Modal 창 출력시 헤더 수정, Form 계정 상태값 강조, ProfileDropdown 길이 초과시 처리 

### ISSUE THREAD

**Issue by juneheel** [Team-SE-MO/semo-react-server#42]
## 📄 설명
- Modal 창 출력시 헤더가 활성화되어있는 상태를 수정합니다.
- Form 계정 조회시 해당 관리 상태값을 강조하는 스타일을 추가합니다.
- 프로필 드롭다운에서 유저 ID의 길이가 늘어날시 말줄임표 등으로 처리해줍니다. 

## 🗓️ TO-DO
- [x] 모달의 z-index를 추가하여 헤더 비활성화 진행
- [x] 사용자 계정 상태값 CSS 진행
- [x] 유저ID에 따른 분기처리 진행
