### ISSUE TITLE
[Batch] 배치 모니터링(메타) 차트 생성 및 CSS 적용

### ISSUE THREAD

**Issue by dabeen-jung** [Team-SE-MO/semo-react-server#48]
## 📄 설명
- 배치 모니터링 차트 생성과 이에 따른 css를 적용합니다

## 🗓️ TO-DO
- [x] 차트 페이지 생성
- [x] 실시간 세션 잡 - 차트 생성
   - [x] css 적용
- [x] CSV 적재 잡  - 차트 생성
  - [ ] css 적용
- [x] 삭제 잡  - 차트 생성
  - [ ] css 적용 

## ➕ ETC
-
