### ISSUE TITLE
[Global] 프로젝트 리팩토링

### ISSUE THREAD

**Issue by taeyeon721** [Team-SE-MO/semo-react-server#49]
## 📄 설명
- 프로젝트 코드에서 리팩토링을 진행합니다.

## 🗓️ TO-DO
- [x] 요약 페이지 컴포넌트 분리
- [x] 비밀번호 변경 후 로그인된 사용자 로그아웃 처리
- [x] Device 페이지에서 장비 추가 버튼 위치 수정
- [x] summary device card에 마우스 hover 이벤트 추가
- [ ] summary icon hover 이벤트 추가
- [x] 헤더 메뉴 추가, App.tsx에 route 추가
- [x] header, footer 로그인, 회원가입 페이지에서 안보이도록 하는 방식 수정
- [x] login, signup 페이지 메인페이지로 이동하는 버튼 추가, login, signup이동 링크 추가 
- [x] table css 정리
- [x] 페이지 컴포넌트 너비 확인
- [x] 요청 페이지 페이지네이션 추가
- [x] 표 인덱스 수정
- [x] 요청 페이지간 이동 버튼 추가
- [x] 유저 관리 페이지 하나로 통합
- [x] 유저 페이지 페이지네이션 추가
- [x] 무한스크롤 추가
- [x] 요약 페이지 5초마다 요청 보내기
- [x] favicon, title 수정
- [x] 로그인, 회원가입 랜덤 이미지 추가
- [x] 테이블 헤더 고정
- [x] url통한 직접 접근 제한
- [x] 유저 관리 css 수정
- [x] 그리드 새로고침 버튼 추가
- [ ] 그리드 필터링 추가
- [x] 화면 비율 1920x1080으로 맞추기
- [x] 필요없는 폴더 삭제
- [ ] 장비 삭제 수정 후 리로드
- [x] 요약페이지 API호출시 새로고침 없애기
